# Generated by Django 5.0.4 on 2024-05-27 13:56

import django.db.models.deletion
import pet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(upload_to=pet.models.description_image_file_path),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("publish_date", models.DateField()),
                ("amount", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to=pet.models.pet_image_file_path)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("total_amounts", models.IntegerField()),
                ("current_amounts", models.IntegerField()),
                ("collection_author", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "descriptions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="pet.description",
                    ),
                ),
            ],
        ),
    ]
