# Generated by Django 5.0.4 on 2024-05-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="descriptions",
            new_name="description",
        ),
    ]
