# Generated by Django 4.1 on 2024-05-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('amount', models.ImageField(upload_to='')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('total_amounts', models.IntegerField()),
                ('current_amounts', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField()),
                ('colection_author', models.CharField(max_length=255)),
                ('descriptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.description')),
            ],
        ),
    ]
