# Generated by Django 5.0.4 on 2024-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0009_bet_lot_lot_current_price"),
        ("user", "0003_remove_user_name_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tracked_lots",
            field=models.ManyToManyField(
                blank=True, related_name="tracked_by", to="fundraising.lot"
            ),
        ),
    ]
