# Generated by Django 5.0.4 on 2024-05-31 17:16

import django.db.models.deletion
import fundraising.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fundraising",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=fundraising.models.fundraising_image_file_path
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=150)),
                ("state", models.CharField(max_length=150)),
                ("money_raised", models.DecimalField(decimal_places=2, max_digits=10)),
                ("money_goal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("end_at", models.DateTimeField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraisings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fundraising",
                "verbose_name_plural": "fundraisings",
                "ordering": ("created_at", "end_at"),
            },
        ),
    ]
