# Generated by Django 5.0.4 on 2024-06-01 16:19

import django.db.models.deletion
import fundraising.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0002_alter_fundraising_money_raised"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name="fundraising",
            old_name="creator",
            new_name="fundraiser",
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to=fundraising.models.lot_image_file_path),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")],
                        default="new",
                        max_length=4,
                    ),
                ),
                (
                    "current_bet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("minimal_bet", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("end_at", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="fundraising.category",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fundraising",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="fundraising.fundraising",
                    ),
                ),
            ],
            options={
                "verbose_name": "lot",
                "verbose_name_plural": "lots",
                "ordering": ("created_at", "end_at"),
            },
        ),
    ]
