# Generated by Django 5.0.4 on 2024-06-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0003_category_rename_creator_fundraising_fundraiser_lot"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="LotCategory",
        ),
    ]
