# Generated by Django 5.0.4 on 2024-06-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0006_alter_lot_current_winner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="fundraising",
            name="city",
        ),
        migrations.RemoveField(
            model_name="fundraising",
            name="state",
        ),
        migrations.AddField(
            model_name="fundraising",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fundraisings",
                to="fundraising.location",
            ),
        ),
    ]
