# Generated by Django 5.0.4 on 2024-06-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0008_rename_minimal_bet_lot_minimal_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="lot",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="fundraising.lot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lot",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
